import React, {useEffect, useState} from 'react';
import {useUiText} from '@site/src/i18n/useUiText';
import {requestSchoolShardNavigation} from './requestSchoolShardNavigation.mjs';

/**
 * A sharded client only contains the page modules it owns. Docusaurus links
 * still know every route, so crossing a shard boundary lands here and performs
 * one normal document navigation to the HTML generated by the owning shard.
 */
export default function SchoolShardReload() {
  const t = useUiText('framework');
  const [retryUrl, setRetryUrl] = useState(null);

  useEffect(() => {
    const result = requestSchoolShardNavigation(window);
    if (!result.started) setRetryUrl(result.retryUrl);
  }, []);

  return (
    <main className="container margin-vert--xl" data-kai-school-shard-reload="">
      <p>{retryUrl ? t.shardFailed : t.shardLoading}</p>
      {retryUrl && <a href={retryUrl}>{t.updateAction}</a>}
    </main>
  );
}
