project_id = "the_kai_project"

[functions.developer-api-keys]
verify_jwt = false

[functions.kai-api]
verify_jwt = false

[functions.agent-session]
verify_jwt = false

[functions.agent-context]
verify_jwt = false
