const assert = require('node:assert/strict');
const test = require('node:test');
const {DefaultSidebarItemsGenerator} = require('@docusaurus/plugin-content-docs/lib/sidebars/generator.js');
const {sortSidebarItems} = require('../scripts/sidebar-ordering.cjs');

const category = (label, slug, items = []) => ({
  type: 'category',
  label,
  link: {type: 'generated-index', slug},
  items,
});
const school = (id, items = []) => category(id, `/category/${id}`, items);

function deepFreeze(value) {
  Object.freeze(value);
  for (const child of Object.values(value)) {
    if (child && typeof child === 'object') deepFreeze(child);
  }
  return value;
}

test('sorts real default-generator category links by rank without moving non-school slots', () => {
  const folderIds = ['kobe-university', 'reference', 'tokyo-university', 'osaka-university', 'kyoto-university'];
  const categoriesMetadata = Object.fromEntries(folderIds.map((id, index) => [id, {
    // A misleading school label must not make an unrelated category sortable.
    label: id === 'reference' ? '東京大学' : `display label ${index}`,
    position: index + 1,
    link: {type: 'generated-index', slug: `/category/${id}`},
  }]));
  const docs = [
    {id: 'intro', title: 'Introduction', source: '@site/docs/intro.md', sourceDirName: '.', sidebarPosition: 0, frontMatter: {}},
    ...folderIds.map((id) => ({
      id: `${id}/exam`, title: 'Exam', source: `@site/docs/${id}/exam.md`, sourceDirName: id, frontMatter: {},
    })),
  ];
  const generated = DefaultSidebarItemsGenerator({
    item: {type: 'autogenerated', dirName: '.'},
    docs,
    categoriesMetadata,
    numberPrefixParser: (filename) => ({filename, numberPrefix: undefined}),
    isCategoryIndex: () => false,
  });
  assert.equal(generated[1].href, undefined);
  assert.equal(generated[1].link.slug, '/category/kobe-university');
  const output = sortSidebarItems(generated);
  assert.equal(output[0], generated[0]);
  assert.deepEqual(output[2], generated[2]);
  assert.deepEqual(output.filter((item) => item.type === 'category').map((item) => item.link.slug), [
    '/category/tokyo-university',
    '/category/reference',
    '/category/kyoto-university',
    '/category/osaka-university',
    '/category/kobe-university',
  ]);
});

test('uses detailed ranks within a major rank and preserves equal-rank school order', () => {
  const input = [
    school('kobe-university'),
    school('nagoya-university'),
    school('tohoku-university'),
    school('osaka-university'),
  ];
  assert.deepEqual(sortSidebarItems(input).map((item) => item.label), [
    'osaka-university',
    'nagoya-university',
    'tohoku-university',
    'kobe-university',
  ]);
});

test('preserves departments, programs and non-year slots while sorting years recursively without mutation', () => {
  const note = {type: 'doc', id: 'admissions'};
  const input = [
    school('kobe-university'),
    // Labels and department slugs alone never identify a school.
    category('東京大学', '/category/tokyo-university-science'),
    school('tokyo-university', [
      category('Second department', '/category/tokyo-university-second', [
        category('2023年度', '/category/second-2023'),
        note,
        category('2025年度', '/category/second-2025'),
        category('2024年度', '/category/second-2024'),
        category('2026', '/category/non-year-label'),
      ]),
      category('First department', '/category/tokyo-university-first'),
    ]),
  ];
  const original = structuredClone(input);
  deepFreeze(input);
  const output = sortSidebarItems(input);
  assert.deepEqual(input, original);
  assert.deepEqual(output[1], input[1]);
  assert.deepEqual(output[0].items.map((item) => item.label), ['Second department', 'First department']);
  assert.deepEqual(output[0].items[0].items.map((item) => item.label || item.id), [
    '2025年度', 'admissions', '2024年度', '2023年度', '2026',
  ]);
  assert.equal(output[0].items[0].items[1], note);
});
