const ACKNOWLEDGEMENTS_COPY = {
  zh: {
    eyebrow: 'Special Thanks',
    title: '特别鸣谢每一位贡献者',
    description: '感谢所有参与代码、文档、题解与纠错的朋友。展开后可查看完整贡献记录。',
    summaryTitle: '查看完整贡献者名单',
    summaryHint: (count) => `包含 ${count} 位 GitHub 贡献者，以及已通过的站内投稿者`,
    githubTitle: 'GitHub 贡献者',
    githubHint: '根据仓库贡献记录整理，并排除 bot 账号。',
    githubContributionCount: (count) => `${count} 次仓库贡献`,
    viewGitHub: '查看 GitHub 统计',
    siteTitle: '站内内容贡献者',
    siteHint: '题解投稿或纠错成功转为 PR 后自动计入。',
    contribute: '参与投稿',
    loading: '正在读取站内贡献记录…',
    unavailable: '站内贡献记录暂时无法读取。',
    empty: '还没有已通过的站内投稿，期待第一位贡献者。',
    siteBreakdown: (solutions, corrections) => `${solutions} 篇题解 · ${corrections} 次纠错`,
    privacy: '这里只展示投稿时使用的公开昵称和已通过数量，不展示邮箱、账号 ID 或待审核内容。',
  },
  ja: {
    eyebrow: 'Special Thanks',
    title: 'すべての貢献者に心から感謝します',
    description: 'コード、文書、解答、訂正に参加してくださった皆さまに感謝します。展開すると完全な一覧を確認できます。',
    summaryTitle: '貢献者の完全な一覧を見る',
    summaryHint: (count) => `GitHub 貢献者 ${count} 人と、承認済みのサイト内投稿者`,
    githubTitle: 'GitHub 貢献者',
    githubHint: 'リポジトリの貢献記録から整理し、bot は除外します。',
    githubContributionCount: (count) => `リポジトリへの貢献 ${count} 件`,
    viewGitHub: 'GitHub の統計を見る',
    siteTitle: 'サイト内コンテンツ貢献者',
    siteHint: '解答投稿または訂正が PR に変換されると自動的に集計されます。',
    contribute: '投稿に参加',
    loading: 'サイト内の貢献記録を読み込み中…',
    unavailable: 'サイト内の貢献記録を現在読み込めません。',
    empty: '承認済みのサイト内投稿はまだありません。最初の貢献をお待ちしています。',
    siteBreakdown: (solutions, corrections) => `解答 ${solutions} 件 · 訂正 ${corrections} 件`,
    privacy: '投稿時の公開ニックネームと承認済み件数のみを表示し、メール、アカウント ID、審査中の内容は表示しません。',
  },
  en: {
    eyebrow: 'Special Thanks',
    title: 'With thanks to every contributor',
    description: 'We are grateful to everyone who improves the code, documentation, solutions, and corrections. Expand the list to view the complete record.',
    summaryTitle: 'View the complete contributor list',
    summaryHint: (count) => `${count} GitHub contributors plus accepted site contributors`,
    githubTitle: 'GitHub contributors',
    githubHint: 'Compiled from repository contribution records with bot accounts excluded.',
    githubContributionCount: (count) => `${count} repository contributions`,
    viewGitHub: 'View GitHub insights',
    siteTitle: 'Site content contributors',
    siteHint: 'Counted after a solution or correction is converted to a pull request.',
    contribute: 'Contribute content',
    loading: 'Loading site contribution records…',
    unavailable: 'Site contribution records are temporarily unavailable.',
    empty: 'No accepted site submissions yet. The first contributor could be you.',
    siteBreakdown: (solutions, corrections) => `${solutions} solutions · ${corrections} corrections`,
    privacy: 'Only the public nickname used for submission and accepted counts are shown—never email addresses, account IDs, or pending content.',
  },
};

const SUPPORT_COPY = {
  zh: {
    title: '支持与合作',
    subtitle: '感谢每一份让开放资料库得以持续维护、不断完善的支持。这里记录合作伙伴与社区贡献，也说明支持方式和我们始终坚持的原则。',
    nav: {
      partners: '合作伙伴',
      community: '社区支持',
      contributors: '贡献者鸣谢',
      principles: '合作原则',
      contact: '联系合作',
    },
    hero: {
      eyebrow: 'Support The Kai Project',
      primaryAction: '查看合作伙伴',
      secondaryAction: '了解合作原则',
      valueOpen: '开放访问',
      valueIndependent: '独立编辑',
      valueCommunity: '社区共建',
    },
    partners: {
      eyebrow: 'Partners',
      title: '与 Kai 一起长期建设',
      description: '感谢通过长期支持或实际协作，帮助项目维护基础设施、完善内容与建设社区的伙伴。所有合作均遵循本页公开原则，并尊重项目的编辑独立性。',
      strategicTitle: '战略合作伙伴',
      strategicEmptyTitle: '合作伙伴信息将在确认后公布',
      strategicEmptyText: '我们正在与长期支持项目的伙伴确认公开介绍；双方确认后的正式信息将在这里展示。',
      sustainingTitle: '长期支持伙伴',
      since: (year) => `自 ${year} 年起`,
      learnMore: '了解合作伙伴',
      visitWebsite: '访问官方网站',
    },
    community: {
      eyebrow: 'Community Support',
      title: '每一种参与，都是对 Kai 的支持',
      description: '加入讨论、分享项目、提交题解、参与纠错或提供自愿赞助，都在帮助这份公开资料库持续成长。',
      joinDiscord: '加入 Discord',
      joinQq: '加入 QQ 群',
      contribute: '参与投稿',
      coffee: '请 Kai 喝杯咖啡',
      coffeeDescription: '如果 Kai 对你有所帮助，可以通过已启用的方式提供一次性、自愿支持。',
      methodsComingSoon: '一次性支持方式正在准备中。分享、投稿与纠错同样是对项目的重要支持。',
      alipay: '支付宝',
      wechat: '微信赞赏码',
      afdian: '爱发电',
      buyMeACoffee: 'Buy Me a Coffee',
      openMethod: '前往支持',
      recipient: (hint) => `收款方：${hint}`,
      voluntaryNote: '赞助不会带来额外的内容权限，也不会影响内容收录或编辑判断。',
      paymentSafety: '付款前请核对收款方信息，并根据自身情况自愿决定是否支持。',
    },
    contributors: {
      eyebrow: 'Built Together',
      title: '由社区共同完善的开放资料库',
      description: 'Kai 的每一篇题解、每一次纠错、每一行代码和文档改进，都离不开贡献者。资金支持与内容贡献是两套独立、同样值得感谢的支持方式。',
    },
    principles: {
      eyebrow: 'Our Commitments',
      title: '我们始终坚持的原则',
      description: '支持让项目走得更远，但不会改变 Kai 对开放访问、社区公平、用户隐私和独立判断的承诺。',
      items: [
        {
          id: 'openAccess',
          title: '核心公开内容持续免费开放',
          text: '项目的核心公开内容——包括题库索引、社区贡献题解、公开备考资料及相关说明——将继续面向公众免费开放访问。赞助、合作或配套服务不会改变这一原则。',
        },
        {
          id: 'nonExclusive',
          title: '开放且不排他的社区',
          text: '任何赞助或合作均不构成排他安排。项目不会因合作关系排斥其他学校、私塾、教育机构或社区贡献者；内容收录与社区参与仍依照统一的项目标准处理。',
        },
        {
          id: 'dataPrivacy',
          title: '用户数据不向合作方提供',
          text: '项目不会因赞助或合作关系，向合作方提供用户的账号信息、学习记录、笔记、投稿记录或其他个人数据。用户自主选择使用第三方服务时，适用该第三方另行公布的条款与隐私政策。',
        },
        {
          id: 'commercialServices',
          title: '商业服务需独立审慎判断',
          text: '项目可能根据实际情况介绍或推荐第三方提供的商业服务。相关介绍或推荐仅供参考，不构成对服务质量、适用性或培训效果的承诺或保证。培训效果因个人基础、投入及其他情况而异，请用户结合自身需要独立、审慎判断。',
        },
      ],
    },
    contact: {
      eyebrow: 'Work With Us',
      title: '成为合作伙伴',
      description: '如果你代表教育机构、社区或相关项目，希望通过长期支持、内容共建或其他方式与 Kai 合作，欢迎联系我们。所有合作均以尊重用户、保持开放和维护编辑独立性为前提。',
      action: '邮件联系我们',
    },
    acknowledgements: ACKNOWLEDGEMENTS_COPY.zh,
  },

  ja: {
    title: '支援・パートナーシップ',
    subtitle: 'オープンな資料アーカイブの継続的な保守と発展を支えてくださる、すべての皆さまに感謝します。このページでは、パートナー、コミュニティからの支援、貢献者、そして私たちの方針をご案内します。',
    nav: {
      partners: 'パートナー',
      community: 'コミュニティ支援',
      contributors: '貢献者への感謝',
      principles: '提携方針',
      contact: '提携について',
    },
    hero: {
      eyebrow: 'Support The Kai Project',
      primaryAction: 'パートナーを見る',
      secondaryAction: '提携方針を見る',
      valueOpen: 'オープンアクセス',
      valueIndependent: '編集の独立性',
      valueCommunity: 'コミュニティ共創',
    },
    partners: {
      eyebrow: 'Partners',
      title: 'Kai とともに長期的な基盤を築く',
      description: 'インフラの維持、コンテンツの充実、コミュニティ運営を、継続的な支援や実際の協働によって支えてくださるパートナーに感謝します。すべての提携は本ページの方針に従い、プロジェクトの編集上の独立性を尊重します。',
      strategicTitle: '戦略的パートナー',
      strategicEmptyTitle: 'パートナー情報は確認後に公開します',
      strategicEmptyText: '継続的に支えてくださるパートナーと公開内容を確認しており、双方の確認が完了した正式情報をここに掲載します。',
      sustainingTitle: '継続支援パートナー',
      since: (year) => `${year} 年より`,
      learnMore: 'パートナーについて',
      visitWebsite: '公式サイトを見る',
    },
    community: {
      eyebrow: 'Community Support',
      title: '一つひとつの参加が Kai の支えになります',
      description: '議論への参加、プロジェクトの共有、解答の投稿、訂正、任意の支援は、いずれもこの公開資料アーカイブの成長につながります。',
      joinDiscord: 'Discord に参加',
      joinQq: 'QQ グループに参加',
      contribute: '投稿に参加',
      coffee: 'Kai にコーヒーを一杯',
      coffeeDescription: 'Kai が役立ったと感じた方は、有効になっている方法から任意の一回支援をお寄せいただけます。',
      methodsComingSoon: '一回支援の方法を準備しています。共有、投稿、訂正も、プロジェクトへの大切な支援です。',
      alipay: 'Alipay',
      wechat: 'WeChat 支援コード',
      afdian: 'Afdian',
      buyMeACoffee: 'Buy Me a Coffee',
      openMethod: '支援ページへ',
      recipient: (hint) => `受取人：${hint}`,
      voluntaryNote: '支援によって追加コンテンツへのアクセス権が付与されたり、掲載・編集上の判断が左右されたりすることはありません。',
      paymentSafety: 'お支払い前に受取人情報をご確認のうえ、ご自身の判断で支援をご検討ください。',
    },
    contributors: {
      eyebrow: 'Built Together',
      title: 'コミュニティとともに育てる公開資料アーカイブ',
      description: '解答、訂正、コード、文書の一つひとつが Kai を支えています。資金による支援とコンテンツへの貢献は、独立した、どちらも大切な支援の形です。',
    },
    principles: {
      eyebrow: 'Our Commitments',
      title: '私たちが守り続ける方針',
      description: '支援はプロジェクトの継続を後押ししますが、オープンアクセス、公平なコミュニティ運営、利用者のプライバシー、独立した判断に関する Kai の方針を変えるものではありません。',
      items: [
        {
          id: 'openAccess',
          title: '中核的な公開コンテンツを無償で公開',
          text: '問題集の索引、コミュニティが投稿した解答、公開されている受験資料および関連説明を含む中核的な公開コンテンツは、今後も一般に無償で公開します。支援、提携、または付加サービスによって、この方針が変更されることはありません。',
        },
        {
          id: 'nonExclusive',
          title: '開かれた非排他的なコミュニティ',
          text: 'いかなる支援または提携も、排他的な関係を意味しません。提携関係を理由として、他の大学、大学院進学塾・予備校、教育機関またはコミュニティ貢献者を排除せず、コンテンツの掲載とコミュニティ参加には共通のプロジェクト基準を適用します。',
        },
        {
          id: 'dataPrivacy',
          title: '利用者データを提携先に提供しない',
          text: '支援または提携関係を理由として、利用者のアカウント情報、学習記録、ノート、投稿履歴その他の個人データを提携先へ提供しません。利用者が自ら第三者サービスを利用する場合は、その第三者が別途定める利用条件およびプライバシーポリシーが適用されます。',
        },
        {
          id: 'commercialServices',
          title: '商用サービスは独立かつ慎重に判断',
          text: '実際の状況に応じて、第三者が提供する有料サービスを紹介または推奨する場合があります。こうした紹介または推奨は、サービスの品質、適合性、または指導効果を保証するものではありません。指導効果は、利用者の基礎力、学習への取り組み、その他の事情により異なるため、ご自身の状況に照らして独立かつ慎重に判断してください。',
        },
      ],
    },
    contact: {
      eyebrow: 'Work With Us',
      title: 'パートナーとして協力する',
      description: '教育機関、コミュニティ、関連プロジェクトとして、継続的な支援、コンテンツの共同制作、その他の形で Kai との連携を希望される場合は、お問い合わせください。すべての提携は、利用者の尊重、公開性、編集上の独立性を前提とします。',
      action: 'メールで問い合わせる',
    },
    acknowledgements: ACKNOWLEDGEMENTS_COPY.ja,
  },

  en: {
    title: 'Support & Partnerships',
    subtitle: 'We are grateful to everyone who helps sustain and improve this open study archive. This page recognizes our partners and community contributors, explains ways to support the project, and sets out the principles we continue to uphold.',
    nav: {
      partners: 'Partners',
      community: 'Community Support',
      contributors: 'Contributors',
      principles: 'Partnership Principles',
      contact: 'Work With Us',
    },
    hero: {
      eyebrow: 'Support The Kai Project',
      primaryAction: 'Meet our partners',
      secondaryAction: 'Read our principles',
      valueOpen: 'Open access',
      valueIndependent: 'Editorial independence',
      valueCommunity: 'Built by the community',
    },
    partners: {
      eyebrow: 'Partners',
      title: 'Building Kai for the long term',
      description: 'We thank the partners whose ongoing support and practical collaboration help maintain our infrastructure, improve our content, and sustain the community. Every partnership follows the principles on this page and respects the project’s editorial independence.',
      strategicTitle: 'Strategic Partner',
      strategicEmptyTitle: 'Partner information will follow after confirmation',
      strategicEmptyText: 'We are confirming the public introduction with the partner supporting Kai for the long term. The agreed details will appear here.',
      sustainingTitle: 'Sustaining Partners',
      since: (year) => `Since ${year}`,
      learnMore: 'About this partner',
      visitWebsite: 'Visit official website',
    },
    community: {
      eyebrow: 'Community Support',
      title: 'Every form of participation supports Kai',
      description: 'Joining discussions, sharing the project, submitting solutions, correcting mistakes, or making a voluntary contribution all help this public study archive continue to grow.',
      joinDiscord: 'Join Discord',
      joinQq: 'Join QQ Group',
      contribute: 'Contribute content',
      coffee: 'Buy Kai a coffee',
      coffeeDescription: 'If Kai has been useful to you, you can make a voluntary one-time contribution through any enabled method.',
      methodsComingSoon: 'One-time support methods are being prepared. Sharing, submitting, and correcting content are equally valuable ways to support Kai.',
      alipay: 'Alipay',
      wechat: 'WeChat appreciation code',
      afdian: 'Afdian',
      buyMeACoffee: 'Buy Me a Coffee',
      openMethod: 'Open support page',
      recipient: (hint) => `Recipient: ${hint}`,
      voluntaryNote: 'Contributions do not unlock additional content and do not influence content inclusion or editorial decisions.',
      paymentSafety: 'Please verify the recipient details before paying and contribute only if you choose to do so.',
    },
    contributors: {
      eyebrow: 'Built Together',
      title: 'An open study archive improved by its community',
      description: 'Every solution, correction, line of code, and documentation improvement helps Kai grow. Financial support and content contributions are separate and equally appreciated forms of support.',
    },
    principles: {
      eyebrow: 'Our Commitments',
      title: 'Principles we continue to uphold',
      description: 'Support helps the project move forward, but it does not change Kai’s commitments to open access, a fair community, user privacy, and independent judgment.',
      items: [
        {
          id: 'openAccess',
          title: 'Core public content remains free',
          text: 'The project’s core public content—including exam indexes, community-contributed solutions, publicly available study materials, and related documentation—will remain freely accessible to the public. Sponsorships, partnerships, and supporting services do not alter this commitment.',
        },
        {
          id: 'nonExclusive',
          title: 'An open, non-exclusive community',
          text: 'No sponsorship or partnership creates an exclusive arrangement. We do not exclude any university, graduate-school preparation provider, educational organization, or community contributor because of a partnership; the same project standards continue to govern content inclusion and community participation.',
        },
        {
          id: 'dataPrivacy',
          title: 'User data is not provided to partners',
          text: 'We do not provide partners with users’ account information, learning records, notes, submission history, or other personal data because of a sponsorship or partnership. If a user independently chooses to use a third-party service, that service’s separately published terms and privacy policy apply.',
        },
        {
          id: 'commercialServices',
          title: 'Commercial services require independent judgment',
          text: 'We may, where appropriate, introduce or recommend paid services offered by third parties. Such introductions or recommendations do not guarantee service quality, suitability, or educational outcomes. Outcomes vary with each person’s background, effort, and circumstances, and users should make their own careful assessment.',
        },
      ],
    },
    contact: {
      eyebrow: 'Work With Us',
      title: 'Become a partner',
      description: 'If you represent an educational organization, community, or related project and would like to support Kai over the long term, collaborate on content, or explore another form of partnership, please contact us. Every partnership is grounded in respect for users, openness, and editorial independence.',
      action: 'Contact us by email',
    },
    acknowledgements: ACKNOWLEDGEMENTS_COPY.en,
  },
};

export function getSupportCopy(language) {
  return SUPPORT_COPY[language] || SUPPORT_COPY.zh;
}
