export default {
  zh: {
    title: '分享备考经验', intro: '推荐一篇有帮助的外部文章，或在本站发表自己的备考经历。',
    external: '推荐外链', internal: '站内原创', titleLabel: '文章标题', url: '原文链接', publishedYear: '首次发布年份',
    publishedHint: '填写原文首次发布年，不是最近编辑年。', markdown: '经验正文（Markdown）', edit: '编辑正文', preview: '预览正文',
    placements: '学校、专攻与报考经历', placement: '报考经历', add: '添加一段报考经历', remove: '移除',
    university: '学校', department: '研究科／学院', program: '专攻', choose: '请选择学校', unknown: '未注明',
    admissionYear: '入学年度（已知时填写）', examYear: '考试年份（参加考试时填写）', season: '考期', summer: '夏入', winter: '冬入',
    seasonRequired: '考期（必填）', chooseSeason: '请选择考期', seasonRequiredMessage: '填写考试年份后，必须选择夏入或冬入。',
    yearHint: '例如 2024 夏试和 2025 冬试通常对应 2025 入学年度；明确的入学时间优先。无法确认时留空，按发布年份归类。',
    scopeHint: '可添加多所学校、多个专攻或不同考期，包括有实质内容的失败经历。仅套磁、计划报考和弃考的学校无需添加。找不到专攻时先选已知的学校／研究科，并在说明中补充。',
    notes: '补充说明（选填）', notesHint: '可说明年份依据、缺少的分类、是否合格，或与已有文章的关系。',
    consent: '我已阅读并同意', cla: '投稿协议（CLA）', externalConsent: '本次仅提交标题、链接和分类，不转载原文，也不代表原作者授予正文许可。', internalConsent: '我确认拥有正文的投稿权利，并同意按投稿协议发布。',
    publicNotice: '提交后会创建公开 GitHub Issue，由维护者核查后收录。请勿填写私密信息。',
    submit: '提交审核', submitting: '正在提交…', login: '登录后投稿', nickname: '请先在个人中心确认公开昵称。',
    consentRequired: '请先确认投稿协议。', unavailable: '投稿服务暂不可用，请稍后重试。', failed: '投稿失败，请检查填写内容后重试。',
    success: '投稿已提交', successHint: '感谢分享备考经历。审核通过后会收录到经验目录，你可以在我的投稿中查看进度。', pendingReview: '等待审核', viewIssue: '查看审核记录', records: '我的投稿', back: '返回经验目录',
    author: '公开投稿署名', mode: '经验贴', duplicate: '同一学校／专攻和考期请勿重复填写。',
  },
  ja: {
    title: '受験体験記を投稿', intro: '役立つ外部記事を紹介するか、自分の体験記を本サイトに投稿できます。',
    external: '外部記事を紹介', internal: '本サイトに投稿', titleLabel: '記事タイトル', url: '原文 URL', publishedYear: '初回公開年',
    publishedHint: '最終更新年ではなく、初めて公開された年です。', markdown: '本文（Markdown）', edit: '本文を編集', preview: '本文をプレビュー',
    placements: '大学・専攻と受験歴', placement: '受験歴', add: '受験歴を追加', remove: '削除',
    university: '大学', department: '研究科・学院', program: '専攻', choose: '大学を選択', unknown: '不明',
    admissionYear: '入学年度（分かる場合）', examYear: '受験年（受験した場合）', season: '入試時期', summer: '夏季', winter: '冬季',
    seasonRequired: '入試時期（必須）', chooseSeason: '入試時期を選択', seasonRequiredMessage: '受験年を入力した場合は、夏季または冬季を選択してください。',
    yearHint: '2024 年夏・2025 年冬の入試は通常 2025 年度入学です。明記された入学時期を優先し、不明な場合は空欄にすると公開年で分類します。',
    scopeHint: '複数の大学・専攻・入試時期や、詳しい不合格体験も追加できます。問い合わせ・検討・受験辞退のみの大学は追加不要です。専攻が見つからない場合は大学・研究科まで選択し、補足欄に記載してください。',
    notes: '補足（任意）', notesHint: '年度の根拠、不足する分類、合否、既存記事との関係など。',
    consent: '以下を読み、同意します：', cla: '投稿者ライセンス契約（CLA）', externalConsent: 'タイトル・リンク・分類のみを提出し、原文の転載や原著者の許諾を意味しません。', internalConsent: '本文を投稿する権利を有し、CLA に基づく公開に同意します。',
    publicNotice: '送信すると公開 GitHub Issue が作成され、メンテナーが確認します。非公開情報は記載しないでください。',
    submit: 'レビューに送信', submitting: '送信中…', login: 'ログインして投稿', nickname: 'マイページで公開ニックネームを確認してください。',
    consentRequired: 'CLA を確認してください。', unavailable: '投稿サービスを利用できません。後ほど再試行してください。', failed: '送信に失敗しました。入力内容をご確認ください。',
    success: '投稿を受け付けました', successHint: '体験の共有ありがとうございます。承認後、体験記一覧に掲載します。進捗は投稿履歴から確認できます。', pendingReview: '確認待ち', viewIssue: 'レビューを表示', records: '自分の投稿履歴', back: '体験記一覧へ',
    author: '公開投稿者名', mode: '体験記', duplicate: '同じ専攻・入試時期の重複を削除してください。',
  },
  en: {
    title: 'Share an admission story', intro: 'Recommend a useful external article or publish your own preparation story here.',
    external: 'Recommend a link', internal: 'Write on this site', titleLabel: 'Article title', url: 'Original article URL', publishedYear: 'First publication year',
    publishedHint: 'Use the original publication year, rather than the latest edit year.', markdown: 'Story (Markdown)', edit: 'Edit story', preview: 'Preview story',
    placements: 'Universities, programs, and exam attempts', placement: 'Exam attempt', add: 'Add an exam attempt', remove: 'Remove',
    university: 'University', department: 'Graduate school', program: 'Program', choose: 'Choose a university', unknown: 'Unspecified',
    admissionYear: 'Admission year (if known)', examYear: 'Exam year (if taken)', season: 'Exam season', summer: 'Summer', winter: 'Winter',
    seasonRequired: 'Exam season (required)', chooseSeason: 'Choose an exam season', seasonRequiredMessage: 'Choose summer or winter when an exam year is provided.',
    yearHint: 'Summer 2024 and winter 2025 usually mean 2025 admission. Explicit enrollment dates take priority. Leave unknown dates blank to use the publication year.',
    scopeHint: 'Add multiple schools, programs, or exam rounds, including substantive unsuccessful applications. Omit schools only contacted, considered, or skipped. If a program is missing, select its known university/graduate school and explain below.',
    notes: 'Review notes (optional)', notesHint: 'Explain the timeline, missing classifications, outcomes, or a related existing article.',
    consent: 'I have read and agree to the', cla: 'Contributor License Agreement (CLA)', externalConsent: 'Only the title, link, and classifications are submitted. This does not reproduce the article or license its author’s content.', internalConsent: 'I have the right to contribute this story and agree to publish it under the CLA.',
    publicNotice: 'Submitting creates a public GitHub Issue for maintainer review. Do not include private information.',
    submit: 'Submit for review', submitting: 'Submitting…', login: 'Sign in to submit', nickname: 'Confirm your public nickname in Personal Center first.',
    consentRequired: 'Please confirm the CLA first.', unavailable: 'The submission service is unavailable. Please try again later.', failed: 'Submission failed. Check your input and try again.',
    success: 'Your story is submitted', successHint: 'Thanks for sharing your experience. A maintainer will review it for the directory. You can follow its progress in your submissions.', pendingReview: 'Awaiting review', viewIssue: 'View review', records: 'My submissions', back: 'Back to stories',
    author: 'Public contributor name', mode: 'Admission story', duplicate: 'Remove duplicate classifications for the same exam round.',
  },
};
